spring:
    application:
        name: zero-code-ai
    # mysql
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/zero_code
        username: root
        password: 123456
    profiles:
      active: local

server:
    port: 8123
    servlet:
        context-path: /api

# springdoc-openapi /api/doc.html
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.code.zero.controller
  

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


